services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"  # Secure: localhost only
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "127.0.0.1:8080:80"  # Secure: localhost only
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

  # Main API Application
  api:
    build: .
    ports:
      - "0.0.0.0:8000:8000"  # Public: accessible externally
    environment:
      # API Configuration
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      
      # Security Configuration
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_ECHO=${DATABASE_ECHO}
      
      # Google ADK Configuration
      - ADK_MODEL_PROVIDER=${ADK_MODEL_PROVIDER}
      - ADK_MODEL_NAME=${ADK_MODEL_NAME}
      - ADK_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      
      # Platform Configuration
      - PLATFORM_NAME=${PLATFORM_NAME}
      - PLATFORM_VERSION=${PLATFORM_VERSION}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  pgadmin_data:
