name: Deploy to Hetzner Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HETZNER_HOST }}
        username: ${{ secrets.HETZNER_USER }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        script: |
          cd /home/developer/app/openapi-chat-agent
          git pull origin main
          docker compose down
          docker compose build --no-cache
          docker compose up -d
          docker image prune -f
          echo "Deployment completed successfully!"
